In [30]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt 

# Data Preprocessing 

In [31]:
ds = pd.read_csv('Churn_Modelling.csv')
ds.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [32]:
x = ds.iloc[:,3:13].values
y = ds.iloc[:,13].values

In [34]:
x.astype('int')

array([[     0,      0,    619, ...,      1,      1, 101348],
       [     0,      1,    608, ...,      0,      1, 112542],
       [     0,      0,    502, ...,      1,      0, 113931],
       ...,
       [     0,      0,    709, ...,      0,      1,  42085],
       [     1,      0,    772, ...,      1,      0,  92888],
       [     0,      0,    792, ...,      1,      0,  38190]])

In [33]:
# Encoding Categorical Data
from sklearn.preprocessing import LabelEncoder,OneHotEncoder
labelencoder_x_1 = LabelEncoder()
x[:,1] = labelencoder_x_1.fit_transform(x[:,1])
labelencoder_x_2 = LabelEncoder()
x[:,2] = labelencoder_x_2.fit_transform(x[:,2])
onehotencoder = OneHotEncoder(categorical_features = [1])
x = onehotencoder.fit_transform(x).toarray()
x = x[:,1:]


In [35]:
# Splitting the training set into train set and test set
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x, y, test_size = 0.2, random_state = 0)

In [36]:
# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.fit_transform(x_test)


 # TOWARDS ANN 

In [37]:
import keras
from keras.models import Sequential
from keras.layers import Dense

In [38]:
# Initialising the ANN
classifier = Sequential()

In [41]:
# Adding the input layer and the first hidden layer
classifier.add(Dense(units = 6,kernel_initializer = 'uniform',activation = 'relu', input_dim = 11))

In [42]:
# Adding second hidden layer 
classifier.add(Dense(units = 6,kernel_initializer = 'uniform',activation= 'relu'))

In [43]:
# Adding the output layer
classifier.add(Dense(units = 1,kernel_initializer='uniform', activation= 'sigmoid' ))

In [45]:
# Compiling the ANN
classifier.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

In [46]:
# Fitting ANN to the training set
classifier.fit(x_train,y_train,batch_size=10,epochs=100)

Instructions for updating:
Use tf.cast instead.
Epoch 1/100
8000/8000 [==============================] - ETA: 0s - loss: 0.4908 - acc: 0.794 - 6s 699us/step - loss: 0.4854 - acc: 0.7959
Epoch 2/100
8000/8000 [==============================] - 1s 111us/step - loss: 0.4300 - acc: 0.7960
Epoch 3/100
8000/8000 [==============================] - 1s 115us/step - loss: 0.4248 - acc: 0.7962
Epoch 4/100
8000/8000 [==============================] - 1s 113us/step - loss: 0.4205 - acc: 0.8180
Epoch 5/100
8000/8000 [==============================] - 1s 115us/step - loss: 0.4181 - acc: 0.8239
Epoch 6/100
8000/8000 [==============================] - 1s 115us/step - loss: 0.4158 - acc: 0.8275
Epoch 7/100
8000/8000 [==============================] - 1s 115us/step - loss: 0.4142 - acc: 0.8296
Epoch 8/100
8000/8000 [==============================] - 1s 143us/step - loss: 0.4124 - acc: 0.8312
Epoch 9/100
8000/8000 [==============================] - 1s 125us/step - loss: 0.4116 - acc: 0.8327
Epoch 10/100
8

In [51]:

# Predicting the Test set results
y_pred = classifier.predict(x_test)
y_pred = (y_pred > 0.5)

# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)

In [54]:

cm

array([[1550,   45],
       [ 274,  131]], dtype=int64)

In [55]:
y_pred

array([[False],
       [False],
       [False],
       ...,
       [False],
       [False],
       [False]])